### ISSUE TITLE
Use setTitle() for all Fragments

### ISSUE THREAD

**Issue by TheKeymaster** [TheKeymaster/support-tool-android-app#3]
At the moment all pages do say `Supporttool v3`, but to have a better UX, we should manually set the Title for each fragment. When loading the Fragment like:

https://github.com/TheKeymaster/support-tool-android-app/blob/635e5bfce5d97d566ec33b0fa97dd38b7f2c5dae/app/src/main/java/com/example/philipp/supporttoolv3/MainActivity.java#L71

We should set the Title to e.g. `Login`.

**Comment by Destiny2101** [comment]
done!
